# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - eatpm-dev-krc-002

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: "Deploy Profile"
        required: true
        options:
          - Develop
          # - Stage
          - Production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          # cache: 'pnpm'

      - name: Write environment variables
        run: |
          echo "DB_HOST=$DB_HOST" >> .env
          echo "DB_USER_ID=$DB_USER_ID" >> .env
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
          echo "JWT_KEY=$JWT_KEY" >> .env
          echo "NEXT_PUBLIC_BUILD_SIGNATURE=$(date +'%Y%m%d_%H%M%S')" >> .env
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER_ID: ${{ secrets.DB_USER_ID }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_KEY: ${{ secrets.JWT_KEY }}

      - name: pnpm install, build
        run: |
          pnpm install
          pnpm run build

      - name: Copy static files
        run: |
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./.next/standalone
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.event.inputs.profile }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "eatpm-dev-krc-002"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EF76494C79144610B821AAC61B696FBB }}
